### ISSUE TITLE
Seed -  3D Model in STEP file format

### ISSUE THREAD

**Issue by Max-Delius** [electro-smith/Hardware#18]
It would be nice if the 3d model for the seed could be added in STEP file format so it can be used more easily in KiCad and other open source software.

**Comment by takumi-ogata** [comment]
Hello Max-Delius, 

I'm really sorry for the delay in response. We wanted to let you know that a STEP file is available here: https://github.com/electro-smith/Hardware/tree/master/resources/models/seed
