### ISSUE TITLE
Can you please add the schematic for the Daisy SEED Rev 5

### ISSUE THREAD

**Issue by Tim-Deefield** [electro-smith/Hardware#20]
I cannot find any hardware information/schematic for the Daisy SEED Rev 5 with the WM8731S codec that I just purchased.
Can you please update the Hardware folder with any Rev 5 information that is available.

Also, if a second WM8731S codec is added will Daisy auto-detect this and setup the proper drivers?

Thank you,
-Tim

**Comment by andrewikenberry** [comment]
added in latest PR. 

Thanks for the remind!
