### ISSUE TITLE
PDF for Daisy Seed Rev5 schematic is poorly rendered

### ISSUE THREAD

**Issue by ashgray0** [electro-smith/Hardware#23]
The PDF file Daisy Seed V5 schematic located at Hardware/reference/daisy_seed/Daisy_Seed_Rev5_sch.pdf is rendered at a very low resolution, making it essentially unreadable. However, there is a properly rendered version of the same schematic located at Hardware/doc/daisy_seed/Daisy_Seed_Rev5_sch.pdf. Can you replace the low resolution copy with a properly rendered one? Not a big deal obviously, just thought you should know.

**Comment by andrewikenberry** [comment]
Thanks for pointing this out!
It has been [fixed.](https://github.com/electro-smith/Hardware/blob/master/reference/daisy_seed/Daisy_Seed_Rev5_sch.pdf)
