### ISSUE TITLE
AK4556 typo

### ISSUE THREAD

**Issue by corellmichael** [electro-smith/Hardware#5]
"AD4556" should be labeled as "AK4556" in schematic

**Comment by bjohas** [comment]
Also just found that error. Would be great to correct it, as it helps people less familiar with audio hardware to figure out what's what :) I annotated the PDF as well, attached here.
[ES_Daisy_Patch_Rev4 - annotated.pdf](https://github.com/electro-smith/Hardware/files/5145833/ES_Daisy_Patch_Rev4.-.annotated.pdf)
