### ISSUE TITLE
pinout mismatch

### ISSUE THREAD

**Issue by jpnielsen** [electro-smith/Hardware#6]
On this schematic and image, Pin20 is Analog Ground
https://github.com/electro-smith/DaisyWiki/wiki/2.-Daisy-Seed-Pinout
https://github.com/electro-smith/Hardware/blob/master/reference/daisy_seed/ES_Daisy_Seed_Rev4.pdf

On this image:
https://www.facebook.com/electrosmithco/photos/a.728418737626651/853636301771560
Pin 20 is Audio out 2

**Comment by jpnielsen** [comment]
https://github.com/electro-smith/DaisyWiki/issues/5

**Comment by stephenhensley** [comment]
Thanks for pointing this out! That was a pre-production revision.

@andrewikenberry  I see the issue on the wiki repo got closed, are we good to close this one as well? Not sure if the facebook post can be edited, or anything to show either the correct pinout, or link to the up to date image.

**Comment by andrewikenberry** [comment]
Good catch, I just deleted the Facebook post to avoid any confusion.
